version: '3.8'

services:
  osint-server:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./app:/app
      - ./data:/data
      - ./logs:/logs
    environment:
      - PYTHONPATH=/app
    networks:
      - osint-network
    cap_add:
      - NET_ADMIN
      - NET_RAW
    security_opt:
      - seccomp:unconfined
    # Use command from Dockerfile

networks:
  osint-network:
    driver: bridge

volumes:
  data:
  logs: 